<a href="https://colab.research.google.com/github/Harshil-24/Harshil-24/blob/main/202406101410002.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# 202406101410002.ipynb

**Course:** Mastering Numerical Python with NumPy (IT4047)  
**ER.No:** 202406101410002

## Import Libraries

In [2]:
import numpy as np
np.random.seed(0)
print("NumPy version:", np.__version__)

NumPy version: 2.0.2


## Section 1: Array Creation & Inspection

### np.array()
Create arrays from Python lists.

In [3]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


### np.arange()
Generate evenly spaced values.

In [4]:
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


### np.linspace()
Generate linearly spaced values between two numbers.

In [5]:
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


### np.zeros()
Create array of zeros.

In [6]:
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


### np.ones()
Create array of ones.

In [7]:
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


### np.eye()
Create an identity matrix.

In [8]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### np.random.rand()
Generate uniform random numbers.

In [9]:
arr = np.random.rand(2,3)
print(arr)

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]


### np.random.randn()
Generate standard normal random numbers.

In [10]:
arr = np.random.randn(2,3)
print(arr)

[[ 0.95008842 -0.15135721 -0.10321885]
 [ 0.4105985   0.14404357  1.45427351]]


### np.shape()
Get array shape.

In [11]:
arr = np.arange(12).reshape(3,4)
print('Shape:', np.shape(arr))

Shape: (3, 4)


### np.ndim()
Get array dimensions.

In [12]:
print('Dimensions:', np.ndim(arr))

Dimensions: 2


## Section 2: Array Operations

### np.reshape()
Reshape an array.

In [13]:
a = np.arange(6)
print(a.reshape(2,3))

[[0 1 2]
 [3 4 5]]


### np.transpose()
Transpose a matrix.

In [14]:
arr = np.arange(6).reshape(2,3)
print(arr.T)

[[0 3]
 [1 4]
 [2 5]]


### np.concatenate()
Concatenate arrays.

In [15]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(np.concatenate([a,b], axis=0))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### np.split()
Split arrays into parts.

In [16]:
arr = np.arange(6).reshape(2,3)
print(np.split(arr,2))

[array([[0, 1, 2]]), array([[3, 4, 5]])]


### np.vstack()
Stack arrays vertically.

In [17]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(np.vstack([a,b]))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### np.hstack()
Stack arrays horizontally.

In [18]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(np.hstack([a,b]))

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


## Section 3: Math and Statistical Functions

### np.add()
Add elements.

In [19]:
M = np.random.randint(1,10,(4,4))
print(np.add(M,M))

[[18  4 12 18]
 [10  8  2  8]
 [12  2  6  8]
 [18  4  8  8]]


### np.subtract()
Subtract elements.

In [20]:
print(np.subtract(M,1))

[[8 1 5 8]
 [4 3 0 3]
 [5 0 2 3]
 [8 1 3 3]]


### np.multiply()
Multiply elements.

In [21]:
print(np.multiply(M,2))

[[18  4 12 18]
 [10  8  2  8]
 [12  2  6  8]
 [18  4  8  8]]


### np.divide()
Divide elements.

In [22]:
print(np.divide(M,2))

[[4.5 1.  3.  4.5]
 [2.5 2.  0.5 2. ]
 [3.  0.5 1.5 2. ]
 [4.5 1.  2.  2. ]]


### np.dot()
Matrix multiplication.

In [23]:
print(np.dot(M,M))

[[208  50 110 149]
 [107  35  53  81]
 [113  27  62  86]
 [151  38  84 121]]


### np.mean()
Mean of array.

In [24]:
print('Mean:', np.mean(M))

Mean: 4.5625


### np.median()
Median of array.

In [25]:
print('Median:', np.median(M))

Median: 4.0


### np.std()
Standard deviation.

In [26]:
print('Std:', np.std(M))

Std: 2.5731486062798625


### np.min()
Minimum value.

In [27]:
print('Min:', np.min(M))

Min: 1


### np.max()
Maximum value.

In [28]:
print('Max:', np.max(M))

Max: 9


### np.argmin()
Index of min.

In [29]:
print('Argmin:', np.argmin(M))

Argmin: 6


### np.argmax()
Index of max.

In [30]:
print('Argmax:', np.argmax(M))

Argmax: 0


### np.sum()
Sum of all elements.

In [31]:
print('Sum:', np.sum(M))

Sum: 73


### np.prod()
Product of all elements.

In [32]:
print('Product:', np.prod(M))

Product: 1612431360


## Section 4: Conditional & Logical Operations

### np.where()
Find indices where condition is True.

In [33]:
arr = np.array([5,2,9,2,7,5,3])
print(np.where(arr>4))

(array([0, 2, 4, 5]),)


### np.unique()
Get unique elements.

In [34]:
print(np.unique(arr))

[2 3 5 7 9]


### np.sort()
Sort array.

In [35]:
print(np.sort(arr))

[2 2 3 5 5 7 9]


### np.argsort()
Return sorted indices.

In [36]:
print(np.argsort(arr))

[1 3 6 0 5 4 2]


### np.all()
Check if all elements satisfy condition.

In [37]:
print(np.all(arr>1))

True


### np.any()
Check if any element satisfies condition.

In [38]:
print(np.any(arr>8))

True


## Case Study 1 — Student Performance Analysis

In [39]:
marks = np.random.randint(40,101,(10,3))
subjects = ['Math','Science','English']
print("Marks:\n", marks)

avg_student = np.mean(marks, axis=1)
avg_subject = np.mean(marks, axis=0)
print("\nAverage per student:", avg_student)
print("Average per subject:", dict(zip(subjects, avg_subject)))

for i, s in enumerate(subjects):
    top3 = np.argsort(marks[:,i])[-3:][::-1]
    print(f"\nTop 3 in {s}: indices {top3}, scores {marks[top3,i]}")

above75 = np.where(avg_student > 75)[0]
print("\nStudents with >75% overall:", above75)

min_vals = marks.min(axis=0)
max_vals = marks.max(axis=0)
normalized = (marks - min_vals) / (max_vals - min_vals)
print("\nNormalized:\n", np.round(normalized,3))

combined = np.concatenate([marks, normalized], axis=1)
print("\nCombined shape:", combined.shape)

Marks:
 [[59 54 79]
 [72 41 49]
 [97 72 71]
 [50 92 63]
 [75 51 90]
 [95 68 74]
 [40 40 76]
 [93 45 78]
 [80 92 57]
 [55 44 81]]

Average per student: [64.         54.         80.         68.33333333 72.         79.
 52.         72.         76.33333333 60.        ]
Average per subject: {'Math': np.float64(71.6), 'Science': np.float64(59.9), 'English': np.float64(71.8)}

Top 3 in Math: indices [2 5 7], scores [97 95 93]

Top 3 in Science: indices [8 3 2], scores [92 92 72]

Top 3 in English: indices [4 9 0], scores [90 81 79]

Students with >75% overall: [2 5 8]

Normalized:
 [[0.333 0.269 0.732]
 [0.561 0.019 0.   ]
 [1.    0.615 0.537]
 [0.175 1.    0.341]
 [0.614 0.212 1.   ]
 [0.965 0.538 0.61 ]
 [0.    0.    0.659]
 [0.93  0.096 0.707]
 [0.702 1.    0.195]
 [0.263 0.077 0.78 ]]

Combined shape: (10, 6)


## Case Study 2 — Temperature Patterns

In [40]:
temps = np.random.uniform(20,40,30).round(2)
print("Temperatures:", temps)

print("\nAverage:", np.mean(temps))
print("Max:", np.max(temps))
print("Min:", np.min(temps))

above_avg = np.where(temps > np.mean(temps))[0]
print("\nDays above average:", above_avg)

sorted_idx = np.argsort(temps)
top5 = sorted_idx[-5:][::-1]
print("\nTop 5 hottest days indices:", top5)
print("Top 5 temps:", temps[top5])

temps_weekly = temps.reshape(5,6)
print("\nWeek-wise averages:", np.mean(temps_weekly, axis=1))
print("Week-wise max:", np.max(temps_weekly, axis=1))

Temperatures: [29.   32.26 38.05 21.99 39.4  33.06 23.42 27.16 35.01 32.16 26.5  20.77
 32.69 39.18 33.06 32.7  39.91 31.64 28.29 29.49 32.47 26.76 33.5  26.34
 35.57 38.99 33.25 20.27 32.46 33.47]

Average: 31.294
Max: 39.91
Min: 20.27

Days above average: [ 1  2  4  5  8  9 12 13 14 15 16 17 20 22 24 25 26 28 29]

Top 5 hottest days indices: [16  4 13 25  2]
Top 5 temps: [39.91 39.4  39.18 38.99 38.05]

Week-wise averages: [32.29333333 27.50333333 34.86333333 29.475      32.335     ]
Week-wise max: [39.4  35.01 39.91 33.5  38.99]


## Checklist
- [x] 25+ NumPy functions demonstrated
- [x] 2 case studies included
- [x] Proper markdown headings and comments